// <auto-generated />
using System;
using Infrastructure.AG_EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.AG_EF.Migrations
{
    [DbContext(typeof(AvansGreenDbContext))]
    [Migration("20221025185704_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Domain.Canteen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasWarmMeals")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Canteens");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Canteen");
                });

            modelBuilder.Entity("Core.Domain.CanteenEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CanteenId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CanteenId");

                    b.HasIndex("EmployeeNr")
                        .IsUnique();

                    b.ToTable("CanteenEmployees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanteenId = 3,
                            EmployeeNr = "a0000000",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CanteenId = 1,
                            EmployeeNr = "e1234567",
                            Name = "Naomi de Vries"
                        },
                        new
                        {
                            Id = 3,
                            CanteenId = 2,
                            EmployeeNr = "e2345678",
                            Name = "Peter Smit"
                        },
                        new
                        {
                            Id = 4,
                            CanteenId = 4,
                            EmployeeNr = "e3456789",
                            Name = "Lennart de Groot"
                        });
                });

            modelBuilder.Entity("Core.Domain.MealType", b =>
                {
                    b.Property<int>("MealTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MealTypeId");

                    b.ToTable("MealTypes");

                    b.HasData(
                        new
                        {
                            MealTypeId = 1,
                            Name = "Bread"
                        },
                        new
                        {
                            MealTypeId = 2,
                            Name = "WarmMeal"
                        },
                        new
                        {
                            MealTypeId = 3,
                            Name = "Drink"
                        });
                });

            modelBuilder.Entity("Core.Domain.Packet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CanteenEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("CanteenId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("bit");

                    b.Property<int>("MealTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PickUpTimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PickUpTimeStart")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeOfPickUpByStudent")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CanteenEmployeeId");

                    b.HasIndex("CanteenId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("StudentId");

                    b.ToTable("Packets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanteenId = 3,
                            IsAlcoholic = true,
                            MealTypeId = 3,
                            Name = "Alcoholic beverage and snack",
                            PickUpTimeEnd = new DateTime(2022, 10, 20, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            PickUpTimeStart = new DateTime(2022, 10, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 5.0m
                        },
                        new
                        {
                            Id = 2,
                            CanteenId = 2,
                            IsAlcoholic = false,
                            MealTypeId = 1,
                            Name = "Lunch with two sandwiches",
                            PickUpTimeEnd = new DateTime(2022, 10, 21, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            PickUpTimeStart = new DateTime(2022, 10, 21, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 5.5m
                        });
                });

            modelBuilder.Entity("Core.Domain.PacketProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("PacketId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacketId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductsInPacket");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PacketId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            PacketId = 1,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 3,
                            PacketId = 2,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("Core.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAlcoholic = true,
                            Name = "Bottle of vodka"
                        },
                        new
                        {
                            Id = 2,
                            IsAlcoholic = false,
                            Name = "Panini"
                        },
                        new
                        {
                            Id = 3,
                            IsAlcoholic = false,
                            Name = "Sandwich"
                        },
                        new
                        {
                            Id = 4,
                            IsAlcoholic = false,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 5,
                            IsAlcoholic = false,
                            Name = "Soup"
                        },
                        new
                        {
                            Id = 6,
                            IsAlcoholic = false,
                            Name = "Baguette"
                        });
                });

            modelBuilder.Entity("Core.Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CityOfSchool")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("StudentNr")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityOfSchool = "Breda",
                            DateOfBirth = new DateTime(1998, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "adminmail@avans.nl",
                            Name = "Admin",
                            StudentNr = "a0000000"
                        },
                        new
                        {
                            Id = 2,
                            CityOfSchool = "Breda",
                            DateOfBirth = new DateTime(1998, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "je.boellaard@student.avans.nl",
                            Name = "Joy Boellaard",
                            PhoneNr = "0612345678",
                            StudentNr = "s2182556"
                        },
                        new
                        {
                            Id = 3,
                            CityOfSchool = "Breda",
                            DateOfBirth = new DateTime(2000, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "em.degroot@student.avans.nl",
                            Name = "Emma de Groot",
                            PhoneNr = "0623456789",
                            StudentNr = "s2192233"
                        },
                        new
                        {
                            Id = 4,
                            CityOfSchool = "Tilburg",
                            DateOfBirth = new DateTime(2001, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "b.dejong@student.avans.nl",
                            Name = "Ben de Jong",
                            StudentNr = "s2192344"
                        },
                        new
                        {
                            Id = 5,
                            CityOfSchool = "Breda",
                            DateOfBirth = new DateTime(1999, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "d.li@student.avans.nl",
                            Name = "Diana Li",
                            PhoneNr = "0645678901",
                            StudentNr = "s2184399"
                        });
                });

            modelBuilder.Entity("Core.Domain.BredaCanteen", b =>
                {
                    b.HasBaseType("Core.Domain.Canteen");

                    b.HasDiscriminator().HasValue("BredaCanteen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Breda",
                            HasWarmMeals = true,
                            Name = "LA5"
                        },
                        new
                        {
                            Id = 2,
                            City = "Breda",
                            HasWarmMeals = true,
                            Name = "LD1"
                        },
                        new
                        {
                            Id = 3,
                            City = "Breda",
                            HasWarmMeals = true,
                            Name = "HA1"
                        });
                });

            modelBuilder.Entity("Core.Domain.DenBoschCanteen", b =>
                {
                    b.HasBaseType("Core.Domain.Canteen");

                    b.HasDiscriminator().HasValue("DenBoschCanteen");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            City = "Den Bosch",
                            HasWarmMeals = true,
                            Name = "DH1"
                        },
                        new
                        {
                            Id = 7,
                            City = "Den Bosch",
                            HasWarmMeals = true,
                            Name = "DH5"
                        });
                });

            modelBuilder.Entity("Core.Domain.TilburgCanteen", b =>
                {
                    b.HasBaseType("Core.Domain.Canteen");

                    b.HasDiscriminator().HasValue("TilburgCanteen");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            City = "Tilburg",
                            HasWarmMeals = false,
                            Name = "TH1"
                        },
                        new
                        {
                            Id = 5,
                            City = "Tilburg",
                            HasWarmMeals = false,
                            Name = "TH5"
                        });
                });

            modelBuilder.Entity("Core.Domain.CanteenEmployee", b =>
                {
                    b.HasOne("Core.Domain.Canteen", "Canteen")
                        .WithMany()
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canteen");
                });

            modelBuilder.Entity("Core.Domain.Packet", b =>
                {
                    b.HasOne("Core.Domain.CanteenEmployee", null)
                        .WithMany("CreatedPackets")
                        .HasForeignKey("CanteenEmployeeId");

                    b.HasOne("Core.Domain.Canteen", "Canteen")
                        .WithMany()
                        .HasForeignKey("CanteenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.MealType", "MealType")
                        .WithMany()
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Student", "Student")
                        .WithMany("ReservedPackets")
                        .HasForeignKey("StudentId");

                    b.Navigation("Canteen");

                    b.Navigation("MealType");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Core.Domain.PacketProduct", b =>
                {
                    b.HasOne("Core.Domain.Packet", "Packet")
                        .WithMany("Products")
                        .HasForeignKey("PacketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Packet");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Core.Domain.CanteenEmployee", b =>
                {
                    b.Navigation("CreatedPackets");
                });

            modelBuilder.Entity("Core.Domain.Packet", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Core.Domain.Student", b =>
                {
                    b.Navigation("ReservedPackets");
                });
#pragma warning restore 612, 618
        }
    }
}
